// frontend/src/utils/scheduledFreightHelper.js

/**
 * Official Indian Railways Scheduled Time-Tabled Goods / Freight Catalog
 * Based on FOIS (Freight Operations Information System, CRIS) standards.
 */

export const SCHEDULED_FREIGHT_TRAINS = [
  {
    trainNo: "G-BOXN-401",
    train_no: "G-BOXN-401",
    trainName: "Ballari Iron Ore Scheduled Heavy Freight",
    train_name: "Ballari Iron Ore Scheduled Heavy Freight",
    type: "GOODS",
    train_type: "GOODS",
    category: "FREIGHT",
    subCategory: "HEAVY_HAUL",
    rakeType: "BOXN",
    rakeCategory: "Open High-Sided Wagon",
    commodity: "Iron Ore Lump / Fines",
    locoClass: "WAG-9H",
    traction: "25kV AC Electric",
    isElectric: true,
    isFreight: true,
    isTimeTabled: true,
    grossTonnage: 5200,
    wagonCount: 58,
    maxSpeedKmph: 75,
    source: "Ballari Goods Yard (BAY)",
    destination: "Mangaluru Port Trust (MAQ)",
    dep: "20:30",
    arr: "21:15",
    departure: "20:30",
    arrival: "21:15",
    scheduledWindow: "20:30–21:15",
    operatingDays: ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"],
    priority: 52,
  },
  {
    trainNo: "22003",
    train_no: "22003",
    trainName: "Whitefield CONCOR Double-Stack Container Express",
    train_name: "Whitefield CONCOR Double-Stack Container Express",
    type: "GOODS",
    train_type: "GOODS",
    category: "CONTAINER",
    subCategory: "TIME_TABLE_FREIGHT",
    rakeType: "BLCA",
    rakeCategory: "Bogie Low Platform Container Flat",
    commodity: "EXIM ISO Sea Shipping Containers",
    locoClass: "WAG-9H",
    traction: "25kV AC Electric",
    isElectric: true,
    isFreight: true,
    isTimeTabled: true,
    grossTonnage: 3800,
    wagonCount: 45,
    maxSpeedKmph: 100,
    source: "Hubballi Freight Terminal (UBL)",
    destination: "Inland Container Depot Whitefield (WFD)",
    dep: "19:15",
    arr: "19:40",
    departure: "19:15",
    arrival: "19:40",
    scheduledWindow: "19:15–19:40",
    operatingDays: ["MON", "WED", "FRI", "SUN"],
    priority: 68,
  },
  {
    trainNo: "G-COAL-601",
    train_no: "G-COAL-601",
    trainName: "Kudgi NTPC Thermal Coal Scheduled Special",
    train_name: "Kudgi NTPC Thermal Coal Scheduled Special",
    type: "GOODS",
    train_type: "GOODS",
    category: "FREIGHT",
    subCategory: "POWER_SECTOR_PRIORITY",
    rakeType: "BOBRN",
    rakeCategory: "Rapid Discharge Hopper Wagon",
    commodity: "Thermal Power Grade Coal",
    locoClass: "WAG-12B",
    traction: "25kV AC Electric",
    isElectric: true,
    isFreight: true,
    isTimeTabled: true,
    grossTonnage: 5800,
    wagonCount: 59,
    maxSpeedKmph: 75,
    source: "Ballari Goods Yard (BAY)",
    destination: "Kudgi Super Thermal Power Station Siding (KDGI)",
    dep: "14:10",
    arr: "14:55",
    departure: "14:10",
    arrival: "14:55",
    scheduledWindow: "14:10–14:55",
    operatingDays: ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"],
    priority: 65,
  },
  {
    trainNo: "00621",
    train_no: "00621",
    trainName: "Kaveri Scheduled Parcel Cargo Express (PCET)",
    train_name: "Kaveri Scheduled Parcel Cargo Express (PCET)",
    type: "GOODS",
    train_type: "GOODS",
    category: "PARCEL",
    subCategory: "TIME_TABLE_CARGO",
    rakeType: "VPH",
    rakeCategory: "High Capacity Parcel Van Rake",
    commodity: "E-Commerce, Perishables & Express Cargo",
    locoClass: "WAP-7",
    traction: "25kV AC Electric",
    isElectric: true,
    isFreight: true,
    isTimeTabled: true,
    grossTonnage: 2100,
    wagonCount: 24,
    maxSpeedKmph: 110,
    source: "Yesvantpur Junction (YPR)",
    destination: "Howrah Goods Terminal (HWH)",
    dep: "11:20",
    arr: "11:45",
    departure: "11:20",
    arrival: "11:45",
    scheduledWindow: "11:20–11:45",
    operatingDays: ["TUE", "THU", "SAT"],
    priority: 72,
  },
  {
    trainNo: "G-BCN-502",
    train_no: "G-BCN-502",
    trainName: "Bagalkote & Wadi Cement Scheduled Express",
    train_name: "Bagalkote & Wadi Cement Scheduled Express",
    type: "GOODS",
    train_type: "GOODS",
    category: "FREIGHT",
    subCategory: "CEMENT_BULK",
    rakeType: "BCNHL",
    rakeCategory: "Covered Bagged Commodity Wagon",
    commodity: "Bagged Portland Cement",
    locoClass: "WDG-4D",
    traction: "Diesel Electric",
    isElectric: false,
    isFreight: true,
    isTimeTabled: true,
    grossTonnage: 4200,
    wagonCount: 58,
    maxSpeedKmph: 65,
    source: "Bagalkote Cement Works Siding (BGK)",
    destination: "Hubballi Freight Complex (UBL)",
    dep: "19:00",
    arr: "19:45",
    departure: "19:00",
    arrival: "19:45",
    scheduledWindow: "19:00–19:45",
    operatingDays: ["MON", "WED", "FRI", "SUN"],
    priority: 48,
  },
  {
    trainNo: "22001",
    train_no: "22001",
    trainName: "Garuda Dedicated Speed Freight Liner",
    train_name: "Garuda Dedicated Speed Freight Liner",
    type: "GOODS",
    train_type: "GOODS",
    category: "CONTAINER",
    subCategory: "TIME_TABLE_FREIGHT",
    rakeType: "BLCA",
    rakeCategory: "Double Stack Container Flat",
    commodity: "High-Value Electronic & Manufacturing Container Cargo",
    locoClass: "WAG-9H",
    traction: "25kV AC Electric",
    isElectric: true,
    isFreight: true,
    isTimeTabled: true,
    grossTonnage: 4100,
    wagonCount: 45,
    maxSpeedKmph: 100,
    source: "JNPT Port Container Yard, Navi Mumbai (JNPT)",
    destination: "Tughlakabad ICD Terminal, New Delhi (TKD)",
    dep: "08:15",
    arr: "08:45",
    departure: "08:15",
    arrival: "08:45",
    scheduledWindow: "08:15–08:45",
    operatingDays: ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"],
    priority: 75,
  },
  {
    trainNo: "G-BTPN-801",
    train_no: "G-BTPN-801",
    trainName: "MRPL Petroleum Tanker Scheduled Special",
    train_name: "MRPL Petroleum Tanker Scheduled Special",
    type: "GOODS",
    train_type: "GOODS",
    category: "FREIGHT",
    subCategory: "POL_PETROLEUM",
    rakeType: "BTPN",
    rakeCategory: "Bogie Petroleum Tanker Wagon",
    commodity: "High Speed Diesel / Petrol (POL)",
    locoClass: "WDG-4D",
    traction: "Diesel Electric",
    isElectric: false,
    isFreight: true,
    isTimeTabled: true,
    grossTonnage: 3900,
    wagonCount: 50,
    maxSpeedKmph: 60,
    source: "Mangaluru MRPL Refinery Siding",
    destination: "Hassan Petroleum Depot (HAS)",
    dep: "16:20",
    arr: "17:05",
    departure: "16:20",
    arrival: "17:05",
    scheduledWindow: "16:20–17:05",
    operatingDays: ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"],
    priority: 60,
  },
  {
    trainNo: "G-STEE-102",
    train_no: "G-STEE-102",
    trainName: "JSW Toranagallu Steel Scheduled Special",
    train_name: "JSW Toranagallu Steel Scheduled Special",
    type: "GOODS",
    train_type: "GOODS",
    category: "FREIGHT",
    subCategory: "STEEL_RAIL",
    rakeType: "BRNA",
    rakeCategory: "Bogie Steel & Rail Wagon",
    commodity: "Finished Heavy Steel Coils & Billets",
    locoClass: "WAG-9",
    traction: "25kV AC Electric",
    isElectric: true,
    isFreight: true,
    isTimeTabled: true,
    grossTonnage: 4800,
    wagonCount: 45,
    maxSpeedKmph: 70,
    source: "JSW Vijayanagar Works Siding (TNGL)",
    destination: "Chennai Harbour Siding (MAS)",
    dep: "22:15",
    arr: "23:00",
    departure: "22:15",
    arrival: "23:00",
    scheduledWindow: "22:15–23:00",
    operatingDays: ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"],
    priority: 55,
  }
];

export function getScheduledFreightForTrack(trackId = "") {
  const normId = String(trackId).toUpperCase();
  // Filter freight matching track or return representative mix for the region
  const matches = SCHEDULED_FREIGHT_TRAINS.filter((t) => {
    if (normId.includes("BAY") || normId.includes("HPT")) {
      return ["G-BOXN-401", "G-COAL-601", "G-STEE-102", "G-BTPN-801"].includes(t.trainNo);
    }
    if (normId.includes("BGK") || normId.includes("GDG")) {
      return ["G-COAL-601", "G-BCN-502"].includes(t.trainNo);
    }
    if (normId.includes("AGL") || normId.includes("UNK") || normId.includes("UBL")) {
      return ["22003", "00621", "G-BCN-502", "G-BOXN-401"].includes(t.trainNo);
    }
    if (normId.includes("BCT") || normId.includes("ADI") || normId.includes("NDLS")) {
      return ["22001", "00621"].includes(t.trainNo);
    }
    if (normId.includes("SBC") || normId.includes("YPR") || normId.includes("MAS")) {
      return ["22003", "00621", "G-STEE-102"].includes(t.trainNo);
    }
    return false;
  });

  if (matches.length > 0) return matches;
  // Default general corridor mix
  return [SCHEDULED_FREIGHT_TRAINS[0], SCHEDULED_FREIGHT_TRAINS[1], SCHEDULED_FREIGHT_TRAINS[3]];
}
